### ISSUE TITLE
The return is ip instead of the domain name

### ISSUE THREAD

**Issue by JianleiZhang** [gin-contrib/location#10]
`	case r.Header.Get(l.headers.host) != "":
		return r.Header.Get(l.headers.host)
`

**Comment by appleboy** [comment]
Could you provide the detail information?

**Comment by tboerger** [comment]
I never had an IP

**Comment by JianleiZhang** [comment]
It heppened when nginx upstream gin

**Comment by JianleiZhang** [comment]
it's my mistake

**Comment by nd2s** [comment]
@JianleiZhang Can you clarify what happened?

**Comment by JianleiZhang** [comment]
```
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
```

**Comment by nd2s** [comment]
@JianleiZhang Thanks, but that doesn't solve the problem. Using my own code for getting the hostname and works now. Has to be a bug in the lib.
