### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by 0xjac** [gin-contrib/location#18]
There have been some changes since the [last v0.0.1 release on 2019-08-17](https://github.com/gin-contrib/location/releases/tag/v0.0.1), including support for [configurable headers](https://github.com/gin-contrib/location/pull/17).

Could we have a new release with those features? Thanks

**Comment by appleboy** [comment]
See https://github.com/gin-contrib/location/releases/tag/v0.0.2 thanks.
