### ISSUE TITLE
Which package to import?

### ISSUE THREAD

**Issue by JianleiZhang** [gin-contrib/location#7]
```cannot use location.Default() (type "github.com/gin-gonic/gin".HandlerFunc) as type "gopkg.in/gin-gonic/gin.v1".HandlerFunc in argument to router.Use```

**Comment by appleboy** [comment]
Could you provide example code?

**Comment by tboerger** [comment]
Can't confirm that, latest version only refers to gopkg.in

**Comment by aequasi** [comment]
I get this same error too

```

import (
    "gopkg.in/gin-gonic/gin.v1"
    "gopkg.in/gin-contrib/cors.v1"
    "github.com/gin-contrib/location"
)


func main() {
    r := gin.Default()
    r.Use(cors.New(cors.Config{
        AllowAllOrigins:  true,
        AllowMethods:     []string{"GET", "OPTIONS"},
        AllowHeaders:     []string{"Origin", "Content-Type"},
        ExposeHeaders:    []string{"Content-Length"},
        AllowCredentials: true,
        MaxAge:           12 * time.Hour,
    }))
    r.Use(location.Default())
}
```

**Comment by appleboy** [comment]
@aequasi I try your example code. It is working for me.

Maybe update your import package.

```
go get -u -v gopkg.in/gin-gonic/gin.v1
go get -u -v gopkg.in/gin-contrib/cors.v1
go get -u -v github.com/gin-contrib/location
```

**Comment by aequasi** [comment]
Still doesn't work

./main.go:line: cannot use location.Default() (type "gopkg.in/gin-gonic/gin.v1".HandlerFunc) as type ".../vendor/gopkg.in/gin-gonic/gin.v1".HandlerFunc in argument to r.Use

**Comment by appleboy** [comment]
@aequasi Can you help to try to import `github.com/gin-gonic/gin` instead of `gopkg.in/gin-gonic/gin.v1`?

Thanks

**Comment by aequasi** [comment]
```
cannot find package "gopkg.in/gin-gonic/gin"
```

Can't `go get` it either.

**Comment by appleboy** [comment]
`gopkg.in/gin-gonic/gin.v1`

**Comment by appleboy** [comment]
You missing some words `v1`

**Comment by aequasi** [comment]
Ah, i misread. 

tried importing from github

```
vendor/github.com/gin-gonic/gin' has no buildable Go source files
```

Error on `gin.Default()`

**Comment by aequasi** [comment]
Ah, i misread that.

Still get the same error as OP. (and one with cors)

**Comment by igor-klimenok** [comment]
@aequasi I fixed that problem by changing imports in "cors.go" and "config.go" files  
Just replace olg imports "github.com/gin-gonic/gin" to "gopkg.in/gin-gonic/gin.v1" and try rebuild project.

That solution works fine for me.
Hope, that I can help you with that problem

**Comment by appleboy** [comment]
@igor-klimenok I recommend replace `gopkg.in/gin-gonic/gin.v1` with `github.com/gin-gonic/gin`.
